### ISSUE TITLE
within_MNI.txt for new MNI152 mask

### ISSUE THREAD

**Issue by alexenge** [NeuroStat/GenerateNull#2]
First of all, thank you for providing this tremendously useful tutorial and code for performing FSN analyses for ALE meta-analyses.

In GingerALE version 3.0 (Feb. 2019, see [change log](http://www.brainmap.org/ale/readme.html)), they have added a new [MNI152](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Atlases) brain mask which, according to the tutorial on the Brainmap website, is preferred over the previous MNI mask.

I wondered if it would be possible reflect this change in the FSN analysis? For this, a new text file with all the coordinates of the new mask (akin to the old [within_MNI.txt](https://github.com/NeuroStat/GenerateNull/blob/master/within_MNI.txt)) would be needed. Would you be able to provide such a file? Or could you tell me how you extracted the coordinates from the old MNI mask so I can create the new within_MNI152.txt file myself (and share it)?

Thank you in advance for your efforts!

**Comment by HBossier** [comment]
I think part of the code to generate this within_MNI.txt file was as following:

```
# Code to convert coordinates
MNI<-c(39,57,36)
toxyz<-function(x,origin) ((x-origin)*2)*c(-1,1,1)           

# Convert the allvox object and write as .txt
allvox.MNI <- array(data=NA,dim=c(dim(allvox)[1],3))
for (i in 1:dim(allvox)[1]) {
  allvox.MNI[i,]<-as.numeric(toxyz(allvox[i,1:3], MNI))
}
write.table(allvox.MNI,"within_MNI.txt",quote=FALSE,row.names=FALSE,col.names=FALSE)
```

However this also depends on an R object `allvox` which I don't seem to find back. I think this can be re-created by reading into R one of the new masks that should contain the coordinates (each row is 1 coordinate in MNI space) but I'm not sure.
