### ISSUE TITLE
Sample sizes for null studies get sampled incorrectly

### ISSUE THREAD

**Issue by alexenge** [NeuroStat/GenerateNull#4]
In the current implementation of [GenerateNull.R](https://github.com/NeuroStat/GenerateNull/blob/master/GenerateNull.R), `nvect` is supposed to be a vector of observed sample sizes from which the new sample sizes of the null studies are randomly drawn. Right now, however, `nvect` is being assigned outside of the `for` loop over the observed studies. It will therefore only contain a single number (i.e., the sample size of the last study in the data set) instead of a vector of all the sample sizes.

Because of the behaviour of `sample()`, the downstream effect of this isn't actually all that easy to spot – if it's provided with a single number (like right now), it samples a random value between 1 and this number. If provided with a vector, it picks a random value from the vector (which is what we would want here for the null studies).

This can easily be fixed by moving the assignment of `nvect` into to the `for` loop, which yields the expected behavior.

**Comment by HBossier** [comment]
I see, yes I agree. Thanks for spotting that!
